import { useEffect } from 'react'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { useWebId, useLoggedIn, useAuthentication } from 'swrlit'

export default function Home() {
  const webId = useWebId()
  const loggedIn = useLoggedIn()
  const { login, logout } = useAuthentication()

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        {
          (loggedIn === undefined) ? (
            <div>loading...</div>
          ) : (
            loggedIn ? (
              <div>
                <div>welcome to hypey!</div>
                <button onClick={() => logout()}>log out</button>
              </div>
            ) : (
              <div>
                <button onClick={() => {
                  login({ oidcIssuer: "https://inrupt.net", redirectUrl: window.location.href, clientName: "Hypey" })
                }}>Log in</button>
              </div>
            )
          )
        }

      </main >
    </div >
  )
}
